TheDisciplineOfIT/Models/Courses.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TheDisciplineOfIT.Models
{
    public class Courses
    {
        [Key]
        public string CourseID { get; set; }
        public string CourseName { get; set; }

        public Courses(ICollection<Units> units)
        {
            Units = units;
        }

        public ICollection<Units> Units { get; set; }
    }
}

TheDisciplineOfIT/Models/ErrorViewModel.cs
using System;

namespace TheDisciplineOfIT.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TheDisciplineOfIT/Models/Person.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TheDisciplineOfIT.Models
{
    public abstract class Person
    {
        public int ID { get; set; }

        [Required]
        [StringLength(50)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z]*$")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Required]
        [RegularExpression(@"^[A-Z]+[a-zA-Z]*$")]
        [StringLength(50, ErrorMessage = "First name cannot be longer than 50 characters.")]
        [Column("FirstName")]
        [Display(Name = "First Name")]
        public string FirstMidName { get; set; }

        [Display(Name = "Full Name")]
        public string FullName
        {
            get
            {
                return LastName + ", " + FirstMidName;
            }
        }
    }
}

TheDisciplineOfIT/Models/Request.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TheDisciplineOfIT.Models
{
    public class Request
    {
        [Key]
        public string RequestID { get; set; }
        public string Status { get; set; }


        public ICollection<Students> StudentID { get; set; }
        public ICollection<Units> UnitName { get; set; }
        public ICollection<Resources> ResourceName { get; set; }


        public Request(ICollection<Units> unitName)
        {
            UnitName = unitName;
        }
        public Request(ICollection<Students> studentid)
        {
            StudentID = studentid;
        }
        public Request(ICollection<Resources> resourceName)
        {
            ResourceName = resourceName;
        }
    }
}

TheDisciplineOfIT/Models/Resources.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace TheDisciplineOfIT.Models
{
    public class Resources
    {
        [Key]
        public string ResourceID { get; set; }
        public string ResourceName { get; set; }
        public int ResourceValue { get; set; }
        public int ResourceQuantity { get; set; }

        public ICollection<Units> Units { get; set; }
    }
}

TheDisciplineOfIT/Models/Students.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TheDisciplineOfIT.Models;

namespace TheDisciplineOfIT.Models
{
    public class Students : Person
    {
        [Key]
        public int StudentID { get; set; }

        public ICollection<Courses> Courses { get; set; }
    }
}

TheDisciplineOfIT/Models/Teachers.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TheDisciplineOfIT.Models;

namespace TheDisciplineOfIT.Models
{
    public class Teachers : Person
    {
        [Key]
        public int TeacherID { get; set; }

        public ICollection<Units> Units { get; set; }
    }
}

TheDisciplineOfIT/Models/Units.cs
using System;
using System.ComponentModel.DataAnnotations;
using TheDisciplineOfIT.Models;
using System.Collections.Generic;

namespace TheDisciplineOfIT.Models
{
    public class Units
    {
        [Key]
        public string UnitID { get; set; }
        public string UnitName { get; set; }

        public ICollection<Teachers> Teachers { get; set; }
    }
}

TheDisciplineOfIT/Controllers/AllocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TheDisciplineOfIT.Controllers
{
    public class AllocationController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

TheDisciplineOfIT/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TheDisciplineOfIT.Models;

namespace TheDisciplineOfIT.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Courses()
        {
            return View();
        }
        public IActionResult Teachers()
        {
            return View();
        }
        public IActionResult Units()
        {
            return View();
        }
        public IActionResult Resources()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TheDisciplineOfIT/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TheDisciplineOfIT.Controllers
{
    public class RequestController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Courses()
        {
            return View();
        }
        public IActionResult Resources()
        {
            return View();
        }
        public IActionResult Teachers()
        {
            return View();
        }
        public IActionResult Units()
        {
            return View();
        }
    }
}

TheDisciplineOfIT/Controllers/ResourcesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TheDisciplineOfIT.Controllers
{
    public class ResourcesController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

TheDisciplineOfIT/Views/Allocation/Index.cshtml
@{
    ViewData["Title"] = "Request Resources";
}
<div>
    <h1 class="display-4">Welcome to Resource Request</h1>
    <p>Current Requests</p>
    <table>
        <thead>
            <tr>
                <td>RequestID</td>
                <td>StudentID</td>
                <td>StudentName</td>
                <td>Request Date</td>
                <td>Approval Status</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>R001</td>
                <td>s4654654</td>
                <td>Anuj</td>
                <td>03/08/2022</td>
                <td>Approved</td>
            </tr>
            <tr>
                <td>R002</td>
                <td>s4785784</td>
                <td>Suman</td>
                <td>05/08/2022</td>
                <td>Denied</td>
            </tr>
            <tr>
                <td>R003</td>
                <td>s6784958</td>
                <td>Sital</td>
                <td>30/08/2022</td>
                <td>In Review</td>
            </tr>
        </tbody>
    </table>
</div>

TheDisciplineOfIT/Views/Home/Courses.cshtml
@{
    ViewData["Title"] = "Courses";
}
<div>
    <h4>Bachelor of Information Technology</h4>
    <ul>
        <li>Introduction to Information Technology</li>
        <li>Introduction to Cyber Security</li>
        <li>Intoduction to Data Science</li>
        <li>Applied Project</li>
    </ul>
    <h4>Bachelor of Cyber Security</h4>
    <ul>
        <li>Introduction to Information Technology</li>
        <li>Introduction to Cyber Security</li>
        <li>Advanced Cyber Security</li>
        <li>Applied Project</li>
    </ul>
    <h4>Bachelor of Data Science</h4>
    <ul>
        <li>Introduction to Information Technology</li>
        <li>Introduction to Data Science</li>
        <li>Advanced Data Science</li>
        <li>Applied Project</li>
    </ul>
</div>

TheDisciplineOfIT/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to The Discipline of IT</h1>
    <p>Learn about IT <a href="/Home/Courses">Courses</a>, <a href="/Home/Units">Units</a>, <a href="/Home/Teachers">Teachers</a>, and <a href="/Home/Resources">Resources</a> provided at <a href="https://www.vu.edu.au">VU</a>. </p>
</div>

TheDisciplineOfIT/Views/Home/Resources.cshtml
@{
    ViewData["Title"] = "Resources";
}
<div>
    <h4>iPad - RES001</h4>
    <p>Provided to students who want to create and test ios and ipados apps.</p>
    <h4>Android Phone - RES002</h4>
    <p>Provided to students who want to create and test android apps.</p>
    <h4>iMac - RES003</h4>
    <p>Provided to students who want to create and test ios, ipados or macos apps.</p>
    <h4>High Performance Computer - RES004</h4>
    <p>Provided to students who want to create and test windows or linux apps, games or anything that requires high performance.</p>
</div>

TheDisciplineOfIT/Views/Home/Teachers.cshtml
@{
    ViewData["Title"] = "Teachers";
}
<div>
    <h1>Our team of highly qualified teachers.</h1>
    <br />
    <br />
    <h4>Dr. Alan Turing</h4>
    <ul>
        <li>PhD. Data Science</li>
        <li>Introduction to Information Technology</li>
        <li>Introduction to Data Science</li>
        <li>Advanced Data Science</li>
    </ul>
    <br />
    <h4>Dr. Tim Cook</h4>
    <ul>
        <li>PhD. Cyber Security</li>
        <li>Introduction to Cyber Security</li>
        <li>Advanced Cyber Security</li>
        <li>Applied Project</li>
    </ul>
</div>

TheDisciplineOfIT/Views/Home/Units.cshtml
@{
    ViewData["Title"] = "Units";
}
<div>
    <h4>Introduction to Information Technology</h4>
    <ul>
        <li>Bachelor of Information Technology</li>
        <li>Bachelor of Cyber Security</li>
        <li>Bachelor of Data Science</li>
    </ul>
    <h4>Introduction to Cyber Security</h4>
    <ul>
        <li>Bachelor of Information Technology</li>
        <li>Bachelor of Cyber Security</li>
    </ul>
    <h4>Intoduction to Data Science</h4>
    <ul>
        <li>Bachelor of Information Technology</li>
        <li>Bachelor of Data Science</li>
    </ul>
    <h4>Advanced Cyber Security</h4>
    <ul>
        <li>Bachelor of Cyber Security</li>
    </ul>
    <h4>Advanced Data Science</h4>
    <ul>
        <li>Bachelor of Data Science</li>
    </ul>
    <h4>Applied Project</h4>
    <ul>
        <li>Bachelor of Information Technology</li>
        <li>Bachelor of Cyber Security</li>
        <li>Bachelor of Data Science</li>
    </ul>
</div>

TheDisciplineOfIT/Views/Request/Index.cshtml
@model IEnumerable<TheDisciplineOfIT.Models.Request>

@{
    ViewData["Title"] = "Request Resources";
}
@*<div>
        <h1 class="display-4">Welcome to Resource Request</h1>

        <h4>Fill in Request Form</h4>
        <form>
            <label for="sid">StudentID</label>
            <input type="text" name="fmane" /><br />
            <label for="rid">ResoureID</label>
            <input type="text" name="rid" /><br />
        </form>
        <button class="btn btn-success">Submit</button>
    </div>*@
<select class="form-select" aria-label="StudentID">
    <option selected>Select Your StudentID</option>
    @foreach (var item in Model)
    {
        <option value="@Html.DisplayFor(modelItem => item.StudentID)">@Html.DisplayFor(modelItem => item.StudentID)</option>
    }
</select>
<select class="form-select" aria-label="ResourceName">
    <option selected>Select Resoure to Request</option>
    @foreach (var item in Model)
    {
        <option value="@Html.DisplayFor(modelItem => item.ResourceName)">@Html.DisplayFor(modelItem => item.ResourceName)</option>
    }
</select>

TheDisciplineOfIT/Views/Request/Success.cshtml
@model TheDisciplineOfIT.Models.Request
@{
    ViewData["Title"] = "Request Successful";
}

TheDisciplineOfIT/Views/Resources/Index.cshtml
@{
    ViewData["Title"] = "Resources";
}
<div>
    <h4>iPad - RES001</h4>
    <p>Provided to students who want to create and test ios and ipados apps.</p>
    <h4>Android Phone - RES002</h4>
    <p>Provided to students who want to create and test android apps.</p>
    <h4>iMac - RES003</h4>
    <p>Provided to students who want to create and test ios, ipados or macos apps.</p>
    <h4>High Performance Computer - RES004</h4>
    <p>Provided to students who want to create and test windows or linux apps, games or anything that requires high performance.</p>
</div>

TheDisciplineOfIT/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - The Discipline Of IT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">The Discipline Of IT</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="Index">Request Resources</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Allocation" asp-action="Index">Allocation</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TheDisciplineOfIT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>